# Generated by Django 4.1.10 on 2023-07-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_asset_directory_assetfacility_asset_facility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directory',
            options={'verbose_name_plural': 'Directories'},
        ),
    ]
