# Generated by Django 4.2.8 on 2023-12-28 22:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_directory_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='postal_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), blank=True, help_text='limit address search results to postal codes starting with these strings', null=True, size=None),
        ),
    ]
