# Generated by Django 4.2.10 on 2024-03-14 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_inputfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_category', models.CharField(choices=[('AB', 'alphabetical'), ('IF', 'inverse_frequency')], default='AB', max_length=2)),
                ('directory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='directory.directory')),
            ],
        ),
    ]
