# Generated by Django 4.2.11 on 2024-03-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_effector'),
        ('directory', '0009_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('uid', models.UUIDField(help_text='uid of neo4j EffectorType node')),
                ('grammatical_number', models.CharField(blank=True, choices=[('S', 'Singular'), ('P', 'Plural')], max_length=1)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=2)),
                ('gender', models.ManyToManyField(related_name='labels', to='accounts.grammaticalgender')),
            ],
        ),
    ]
