# Generated by Django 4.2.8 on 2025-10-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('directory', '0010_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TTL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttl', models.PositiveIntegerField(default=60)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.endpoint')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ttl',
            constraint=models.UniqueConstraint(fields=('endpoint', 'site'), name='unique_endpoint_ttl_per_site'),
        ),
    ]
