# Generated by Django 4.2.8 on 2025-10-23 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('directory', '0011_endpoint_ttl_ttl_unique_endpoint_ttl_per_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.PositiveIntegerField(default=0)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.endpoint')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
        migrations.AddConstraint(
            model_name='timestamp',
            constraint=models.UniqueConstraint(fields=('endpoint', 'site'), name='unique_endpoint_timestamp_per_site'),
        ),
    ]
