# Generated by Django 4.2.8 on 2025-10-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamp',
            name='timestamp',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
