# Generated by Django 4.2.8 on 2025-12-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_alter_timestamp_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputfield',
            name='department',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='inputfield',
            name='organization',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='inputfield',
            name='category',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='inputfield',
            name='commune',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='inputfield',
            name='facility',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='inputfield',
            name='geocoder',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='inputfield',
            name='search',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='inputfield',
            name='situation',
            field=models.BooleanField(null=True),
        ),
    ]
