# Generated by Django 4.2.8 on 2025-12-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0014_inputfield_department_inputfield_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputfield',
            name='tag',
            field=models.BooleanField(null=True),
        ),
    ]
