# Generated by Django 4.2.8 on 2026-01-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0015_inputfield_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='display_facility_organization',
            field=models.BooleanField(help_text="Display facilities which belong (True) or don't belong (False) to the organization or all facilities (null).", null=True),
        ),
    ]
