# Generated by Django 4.2.8 on 2026-01-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0016_setting_display_facility_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='uid',
            field=models.UUIDField(blank=True, help_text='uuid of corresponding neo4j Directory node', null=True),
        ),
    ]
