# Generated by Django 4.2.8 on 2026-02-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0017_directory_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='commune_default',
            field=models.BooleanField(default=False, help_text='Whether to use the commune of the organization as default in the facility creation form.'),
        ),
        migrations.AddField(
            model_name='directory',
            name='department_default',
            field=models.BooleanField(default=False, help_text='Whether to use the department of the organization as default in the facility creation form.'),
        ),
    ]
