# Generated by Django 4.2.28 on 2026-02-17 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('directory', '0018_directory_commune_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='directory', to='sites.site'),
        ),
    ]
