# Generated by Django 4.2.28 on 2026-03-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0019_alter_directory_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='list_navigation',
            field=models.BooleanField(default=False, help_text='Display navigation links in the directory listing.'),
        ),
    ]
