# Generated by Django 4.2.28 on 2026-03-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0020_setting_list_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='term_type',
            field=models.CharField(choices=[('name', 'Name'), ('label', 'Label'), ('synonym', 'Synonym')], default='name', max_length=7),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('label', 'uid', 'grammatical_number', 'language', 'term_type'), name='unique_label_uid_number_language_term_type'),
        ),
    ]
