# Generated by Django 4.2.29 on 2026-04-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0021_add_term_type_to_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='path',
            field=models.CharField(blank=True, default='', help_text='URL path of the directory.', max_length=255),
        ),
    ]
