# Generated by Django 4.2.29 on 2026-04-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0022_setting_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='display_association',
            field=models.BooleanField(default=False, help_text='Display association page.'),
        ),
    ]
