# Generated by Django 4.2.29 on 2026-04-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0023_setting_display_association'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='term_type',
            field=models.CharField(choices=[('name', 'Name'), ('label', 'Label'), ('synonym', 'Synonym'), ('officer', 'Officer category')], default='name', max_length=7),
        ),
    ]
