# Generated by Django 4.2.28 on 2026-05-13 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('directory', '0024_alter_label_term_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='sites.site'),
        ),
    ]
