# Generated by Django 4.2.28 on 2026-05-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0025_directory_site_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='type_slug',
            field=models.BooleanField(default=False, help_text='Use effector type slug in addressbook URL.'),
        ),
    ]
