# Generated by Django 4.2.30 on 2026-06-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0026_add_type_slug_to_setting'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetfacility',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='assetfacility',
            constraint=models.UniqueConstraint(fields=('asset', 'facility'), name='unique_asset_facility'),
        ),
    ]
