# Generated by Django 5.2.17 on 2026-08-25 05:40

import directory.models.core
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0028_neo4j_timestamp_triggers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text="Short stable identifier, e.g. 'santelyon3-prod'.", max_length=64, unique=True)),
                ('display_name', models.CharField(help_text='What the superuser sees in the instance picker.', max_length=255)),
                ('origin', models.URLField(help_text="https origin only, e.g. 'https://santelyon3.fr'.", unique=True, validators=[directory.models.core.validate_peer_origin])),
                ('active', models.BooleanField(default=True, help_text='Unset to retire a peer without deleting its row.')),
                ('outbound', models.BooleanField(default=True, help_text='May this instance read entries FROM that one.')),
                ('inbound', models.BooleanField(default=True, help_text='May that instance read entries FROM this one.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Peer instance',
                'ordering': ['display_name'],
            },
        ),
    ]
