# Generated by Django 5.2.17 on 2026-09-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0029_peerinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrySlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('entry_uid', models.CharField(db_index=True, help_text='uid of the Entry node', max_length=64)),
                ('replaced_at', models.DateTimeField(auto_now_add=True)),
                ('replaced_by', models.CharField(blank=True, help_text='uid of the User who changed it', max_length=64)),
            ],
            options={
                'ordering': ['-replaced_at'],
            },
        ),
    ]
