# Generated by Django 4.1.9 on 2023-06-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0022_alter_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='groups',
            field=models.ManyToManyField(blank=True, to='addressbook.contactgroup'),
        ),
    ]
