# Generated by Django 4.1.10 on 2023-07-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0024_contact_neomodel_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='neomodel_uid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
