# Generated by Django 4.1.10 on 2023-09-05 11:29

from django.db import migrations


def save_org_fk(apps, schema):
    Profile = apps.get_model('addressbook', 'Profile')
    Organization = apps.get_model('facility', 'Organization')
    for profile in Profile.objects.all():
        profile.org = profile.organization.all().first()
        profile.save()
        
def save_organization_m2m(apps, schema):
    Profile = apps.get_model('addressbook', 'Profile')
    Organization = apps.get_model('facility', 'Organization')
    for profile in Profile.objects.all():
        if profile.org:
            profile.organization.add(profile.org)


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0024_historicalprofile_org_profile_org'),
    ]

    operations = [
        migrations.RunPython(save_org_fk, save_organization_m2m)
    ]
