# Generated by Django 4.1.10 on 2023-07-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0025_alter_contact_neomodel_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work')], default='Work', max_length=255),
        ),
    ]
