# Generated by Django 4.1.10 on 2023-09-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0025_auto_20230905_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='organization',
        ),
    ]
