# Generated by Django 4.1.10 on 2023-07-29 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0026_alter_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='addressbook.contact'),
        ),
    ]
