# Generated by Django 4.1.10 on 2023-08-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0028_address_building_alter_address_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='geographical_complement',
            field=models.CharField(blank=True, help_text='Geographical complement to facilitate geolocation', max_length=255, null=True),
        ),
    ]
