# Generated by Django 4.1.10 on 2023-09-16 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0029_address_geographical_complement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='groups',
        ),
    ]
