# Generated by Django 4.1.10 on 2023-09-16 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0030_remove_contact_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactGroup',
        ),
    ]
