# Generated by Django 4.1.10 on 2023-09-25 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0031_delete_contactgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'managed': True},
        ),
    ]
