# Generated by Django 4.2.10 on 2024-03-02 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0021_alter_facility_contact_alter_organization_contact'),
        ('addressbook', '0032_alter_phonenumber_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='facility.organization'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='addressbook.contact'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='organization',
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='facility.organization'),
        ),
    ]
