# Generated by Django 4.2.10 on 2024-03-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0033_historicalprofile_organization_alter_profile_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='house_call',
            field=models.BooleanField(default=False),
        ),
    ]
