# Generated by Django 4.2.11 on 2024-04-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0034_appointment_house_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='tooltip_direction',
            field=models.CharField(choices=[('R', 'Right'), ('L', 'Left'), ('T', 'Top'), ('B', 'Bottom'), ('C', 'Center'), ('A', 'Auto')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='address',
            name='tooltip_permanent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='tooltip_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
