# Generated by Django 4.2.11 on 2024-04-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0035_address_tooltip_direction_address_tooltip_permanent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='tooltip_direction',
            field=models.CharField(choices=[('R', 'right'), ('L', 'left'), ('T', 'top'), ('B', 'bottom'), ('C', 'center'), ('A', 'auto')], default='A', max_length=1),
        ),
    ]
