# Generated by Django 4.2.16 on 2024-11-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0036_alter_address_tooltip_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='public_holidays_zone',
            field=models.CharField(choices=[('alsace-moselle', 'Alsace-Moselle'), ('guadeloupe', 'Guadeloupe'), ('guyane', 'Guyane'), ('la-reunion', 'La Réunion'), ('martinique', 'Martinique'), ('mayotte', 'Mayotte'), ('metropole', 'Métropole'), ('nouvelle-caledonie', 'Nouvelle-Calédonie'), ('polynesie-francaise', 'Polynésie française'), ('saint-barthelemy', 'Saint-Barthélemy'), ('saint-martin', 'Saint-Martin'), ('saint-pierre-et-miquelon', 'Saint-Pierre-et-Miquelon'), ('wallis-et-futuna', 'Wallis-et-Futuna')], default='metropole', max_length=255),
        ),
    ]
