# Generated by Django 4.2.8 on 2025-08-16 21:20

from django.db import migrations

def update_choices(apps, schema_editor):
    YourModel = apps.get_model("addressbook", "PhoneNumber")
    YourModel.objects.filter(type="S").update(type="W")

class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0037_address_public_holidays_zone'),
    ]

    operations = [
        migrations.RunPython(update_choices),
    ]