# Generated by Django 4.2.8 on 2025-08-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0038_auto_20250816_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='type',
            field=models.CharField(choices=[('M', 'Mobile'), ('MW', 'Mobile Work'), ('W', 'Work'), ('F', 'Fax'), ('AS', 'Answering service')], max_length=255),
        ),
    ]
