# Generated by Django 4.2.8 on 2025-08-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0039_alter_phonenumber_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.RemoveField(
            model_name='email',
            name='type',
        ),
    ]
