# Generated by Django 4.2.8 on 2025-08-26 14:28

from django.db import migrations


def delete_skype(apps, schema_editor):
    YourModel = apps.get_model("addressbook", "SocialNetwork")
    YourModel.objects.filter(type="S").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0040_alter_contact_options_remove_email_type'),
    ]

    operations = [
        migrations.RunPython(delete_skype),
    ]
