# Generated by Django 4.2.8 on 2025-08-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0041_auto_20250826_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='type',
            field=models.CharField(choices=[('T', 'X'), ('LI', 'LinkedIn'), ('F', 'Facebook'), ('P', 'Pinterest'), ('I', 'Instagram'), ('YT', 'YouTube'), ('TT', 'TikTok'), ('SC', 'Snapchat'), ('TH', 'Twitch'), ('B', 'Bluesky'), ('M', 'Mastodon')], max_length=255),
        ),
    ]
