# Generated by Django 4.2.8 on 2025-08-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0042_alter_socialnetwork_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='type',
        ),
    ]
