# Generated by Django 4.2.8 on 2025-08-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0043_remove_website_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='website',
            new_name='url',
        ),
    ]
