# Generated by Django 4.2.8 on 2025-11-30 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0044_rename_website_website_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='email',
            unique_together={('contact', 'email')},
        ),
    ]
