# Generated by Django 4.2.8 on 2025-12-01 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0045_alter_email_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='website',
            unique_together={('contact', 'url')},
        ),
    ]
