# Generated by Django 4.2.8 on 2025-12-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0046_alter_website_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonenumber',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='phonenumber',
            unique_together={('contact', 'phone', 'type')},
        ),
    ]
