# Generated by Django 4.2.30 on 2026-06-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0047_alter_phonenumber_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='email',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='phonenumber',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='website',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='email',
            constraint=models.UniqueConstraint(fields=('contact', 'email'), name='unique_contact_email'),
        ),
        migrations.AddConstraint(
            model_name='phonenumber',
            constraint=models.UniqueConstraint(fields=('contact', 'phone', 'type'), name='unique_contact_phone_type'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('contact', 'organization'), name='unique_profile'),
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.UniqueConstraint(fields=('contact', 'url'), name='unique_contact_url'),
        ),
    ]
