# Generated by Django 5.2.15 on 2026-07-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0048_alter_email_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='avatar_access',
            field=models.CharField(default='anonymous', help_text='Minimum role required to see the profile image: anonymous (public), staff (team), administrator.', max_length=20),
        ),
    ]
