# Generated by Django 5.2.17 on 2026-08-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0050_address_updatedat_appointment_updatedat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
