# Generated by Django 5.2.17 on 2026-08-20 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0051_contact_updatedat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
