# Generated by Django 5.2.17 on 2026-08-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0052_delete_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
