# Generated by Django 4.2.10 on 2024-02-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_grammaticalgender_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='effector',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
