# Generated by Django 4.2.23 on 2025-06-21 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_role_description_en_role_description_fr_and_more'),
        ('sites', '0002_alter_domain_unique'),
        ('accounts', '0009_user_effector'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Access Role of the user in the context of the Site', null=True, on_delete=django.db.models.deletion.SET_NULL, to='access.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site'),
        ),
    ]
