# Generated by Django 4.2.8 on 2025-10-29 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_role_description_en_role_description_fr_and_more'),
        ('sites', '0002_alter_domain_unique'),
        ('accounts', '0010_user_role_user_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(help_text='Access Role of the user in the context of the Site', on_delete=django.db.models.deletion.PROTECT, to='access.role')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
        ),
    ]
