# Generated by Django 4.2.8 on 2025-10-29 14:06

from django.db import migrations
import logging

logger = logging.getLogger(__name__)

def create_roles(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    User = apps.get_model("accounts", "User")
    for user  in User.objects.all():
        if user.site and user.role:
            try:
                role, created = Role.objects.get_or_create(
                    user = user,
                    site = user.site,
                    role = user.role
                )
                logger.debug(f"{role=} {created=}")
            except Exception as e:
                logger.error(e)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_role_created_role_updated_role_user'),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
