# Generated by Django 5.2.17 on 2026-10-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_role_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
