# Generated by Django 4.2.28 on 2026-03-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchEmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_uid', models.UUIDField(help_text='Neo4j UID of the User who authored the message')),
                ('subject', models.CharField(max_length=998)),
                ('body', models.TextField()),
                ('sent_at', models.BigIntegerField(help_text='Timestamp in milliseconds when the email was sent')),
                ('recipient_uids', models.JSONField(help_text='List of Neo4j User UIDs who were recipients')),
                ('mailgun_response', models.JSONField(help_text='Full Mailgun API response')),
                ('success', models.BooleanField(help_text='Whether the Mailgun API call succeeded')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
