# Generated by Django 5.2.17 on 2026-09-21 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0029_placeimage'),
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailgunAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Mailgun sending domain, e.g. mail.example.org', max_length=255)),
                ('region', models.CharField(choices=[('eu', 'Europe (api.eu.mailgun.net)'), ('us', 'United States (api.mailgun.net)')], default='eu', help_text='Mailgun region the domain is hosted in', max_length=2)),
                ('sending_key_id', models.CharField(help_text='Mailgun sending key ID (the HTTP basic auth username)', max_length=255)),
                ('api_key', models.CharField(help_text='Mailgun sending key (the HTTP basic auth password)', max_length=255)),
                ('from_email', models.EmailField(help_text="Address the organization's mail is sent from", max_length=254)),
                ('from_name', models.CharField(blank=True, help_text='Display name shown next to the From address; optional', max_length=255)),
                ('active', models.BooleanField(default=True, help_text='Uncheck to fall back to the default credentials without deleting the row')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mailgun_account', to='facility.organization')),
            ],
            options={
                'verbose_name': 'Mailgun account',
                'verbose_name_plural': 'Mailgun accounts',
            },
        ),
    ]
