# Generated by Django 5.2.17 on 2026-09-27 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0030_organization_public_base_url'),
        ('mailer', '0002_mailgunaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('invitation', 'Invitation')], max_length=32)),
                ('subject', models.CharField(max_length=998)),
                ('body', models.TextField()),
                ('content_type', models.CharField(choices=[('html', 'HTML'), ('text', 'Plain text')], default='html', max_length=8)),
                ('body_text', models.TextField(blank=True, help_text='Plain-text alternative sent with an HTML body; derived from the HTML when left empty')),
                ('active', models.BooleanField(default=True, help_text='Uncheck to fall back to the default without deleting the row')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Leave empty for the default used by every organization without its own', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='facility.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'kind'), name='email_template_one_per_organization_and_kind'), models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('kind',), name='email_template_one_default_per_kind')],
            },
        ),
    ]
