# Generated by Django 5.2.17 on 2026-09-27 06:13

from django.db import migrations


def seed(apps, schema_editor):
    """The default invitation template, as the text the code sent until now.

    Plain text on purpose: an HTML default would add an html part to every
    invitation, which is a change of output and belongs to its own step.
    """
    from mailer.defaults import INVITATION_FALLBACK

    EmailTemplate = apps.get_model("mailer", "EmailTemplate")
    if EmailTemplate.objects.filter(organization__isnull=True, kind="invitation").exists():
        return
    EmailTemplate.objects.create(
        organization=None,
        kind="invitation",
        subject=INVITATION_FALLBACK.subject,
        body=INVITATION_FALLBACK.body,
        content_type="text",
        active=True,
    )


def unseed(apps, schema_editor):
    EmailTemplate = apps.get_model("mailer", "EmailTemplate")
    EmailTemplate.objects.filter(organization__isnull=True, kind="invitation").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_emailtemplate'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
