# Generated by Django 5.2.17 on 2026-09-28 07:03

import django.db.models.deletion
import easy_thumbnails.fields
import mailer.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0030_organization_public_base_url'),
        ('mailer', '0004_seed_default_invitation_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to=mailer.models.email_image_path)),
                ('name', models.CharField(help_text='Label shown in the gallery; renaming never changes the file or its URL', max_length=255)),
                ('alt', models.CharField(blank=True, help_text='Describes the picture to people who cannot see it', max_length=255)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField(help_text='In bytes')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_images', to='facility.organization')),
            ],
            options={
                'ordering': ['-created', '-id'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='email_image_name_unique_per_organization')],
            },
        ),
    ]
