# Generated by Django 5.2.17 on 2026-09-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0005_emailimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_uid', models.CharField(db_index=True, max_length=64)),
                ('to_address', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent (accepted by Mailgun)'), ('failed', 'Failed')], default='queued', max_length=8)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Email deliveries',
                'ordering': ['-created', '-id'],
            },
        ),
    ]
