# Generated by Django 5.2.17 on 2026-10-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0006_emaildelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildelivery',
            name='batch_job_uid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='emaildelivery',
            name='error_kind',
            field=models.CharField(blank=True, choices=[('invalid_request', 'Refused as written (address)'), ('misconfigured', 'Our mail configuration'), ('rate_limited', 'Too many messages at once'), ('provider_unavailable', 'Mail service unavailable'), ('unreachable', 'Mail service unreachable'), ('outcome_unknown', 'No answer: outcome unknown')], max_length=32),
        ),
        migrations.AlterField(
            model_name='emaildelivery',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent (accepted by the mail service)'), ('delivered', "Delivered to the recipient's server"), ('deferred', 'Delayed: the service is still trying'), ('bounced', 'Bounced: the address does not receive mail'), ('complained', 'Reported as spam by the recipient'), ('suppressed', 'Not sent: address on the do-not-send list'), ('failed', 'Failed')], default='queued', max_length=16),
        ),
    ]
