# Generated by Django 5.2.17 on 2026-10-05 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0007_email_delivery_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailgunaccount',
            name='webhook_signing_key',
            field=models.CharField(blank=True, help_text="Mailgun's HTTP webhook signing key for this account (Mailgun > Sending > Webhooks). Lets the app trust the delivery events (delivered, bounced...) sent for this account's domain.", max_length=255),
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('provider_event_id', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=16)),
                ('recipient', models.EmailField(blank=True, max_length=254)),
                ('detail', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mailer.emaildelivery')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='unique_provider_event')],
            },
        ),
    ]
