# Generated by Django 5.2.17 on 2026-10-06 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0035_organization_reply_to_email'),
        ('mailer', '0008_email_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(db_index=True, max_length=254)),
                ('reason', models.CharField(choices=[('bounced', 'The mailbox does not exist or does not receive mail'), ('refused', 'Refused as written by the mail service'), ('complained', 'Reported as spam by the recipient'), ('unsubscribed', 'Unsubscribed by the recipient')], max_length=16)),
                ('detail', models.TextField(blank=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailer.emailevent')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_suppressions', to='facility.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('address', 'organization'), name='unique_suppression_per_scope'), models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('address',), name='unique_global_suppression')],
            },
        ),
    ]
