# Generated by Django 4.1.9 on 2023-06-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0041_alter_workforcenetworkedgefacilities_networkedge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workforcenetworkedgefacilities',
            name='public_facing',
        ),
        migrations.RemoveField(
            model_name='workforcenetworkedgeorganizations',
            name='public_facing',
        ),
    ]
