# Generated by Django 4.2.10 on 2024-03-02 02:43

from django.db import migrations, models
import django.db.models.deletion
import workforce.models.limit_choices


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0042_remove_workforcenetworkedgefacilities_public_facing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adeli',
            name='effector_uid',
            field=models.UUIDField(blank=True, help_text='uid of neo4j Effector node', null=True),
        ),
        migrations.AddField(
            model_name='cartevitale',
            name='effector_facility_uid',
            field=models.UUIDField(blank=True, help_text='uid of neo4j LOCATION relationship between Effector and Facility', null=True),
        ),
        migrations.AddField(
            model_name='conventionnement',
            name='effector_facility_uid',
            field=models.UUIDField(blank=True, help_text='uid of neo4j LOCATION relationship between Effector and Facility', null=True),
        ),
        migrations.AddField(
            model_name='rpps',
            name='effector_uid',
            field=models.UUIDField(blank=True, help_text='uid of neo4j Effector node', null=True),
        ),
        migrations.AlterField(
            model_name='adeli',
            name='node',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adeli', to='workforce.networknode'),
        ),
        migrations.AlterField(
            model_name='cartevitale',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carte_vitale', to='workforce.networknode'),
        ),
        migrations.AlterField(
            model_name='conventionnement',
            name='node',
            field=models.ForeignKey(blank=True, limit_choices_to=workforce.models.limit_choices.limit_to_users, null=True, on_delete=django.db.models.deletion.CASCADE, to='workforce.networknode'),
        ),
        migrations.AlterField(
            model_name='rpps',
            name='node',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rpps', to='workforce.networknode'),
        ),
    ]
