# Generated by Django 4.2.30 on 2026-06-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0044_alter_label_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workforcenetworkedgefacilities',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='workforcenetworkedgeorganizations',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='workforcenetworkedgefacilities',
            constraint=models.UniqueConstraint(fields=('networkedge', 'facility'), name='unique_networkedge_facility'),
        ),
        migrations.AddConstraint(
            model_name='workforcenetworkedgeorganizations',
            constraint=models.UniqueConstraint(fields=('networkedge', 'organization'), name='unique_networkedge_organization'),
        ),
    ]
