# Generated by Django 4.2.13 on 2024-06-16 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('survey', '0003_survey_created_survey_end_survey_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='sites.site'),
            preserve_default=False,
        ),
    ]
