# Generated by Django 4.2.8 on 2026-01-31 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iss', models.URLField()),
                ('aud', models.CharField(max_length=255)),
                ('sub', models.CharField(max_length=255)),
                ('iat', models.BigIntegerField()),
                ('email', models.CharField(max_length=255)),
                ('email_verified', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('picture', models.URLField()),
                ('given_name', models.CharField(max_length=255)),
                ('family_name', models.CharField(max_length=255)),
                ('locale', models.CharField(max_length=10)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'indexes': [models.Index(models.F('email'), name='oidc_email_idx'), models.Index(models.F('sub'), name='oidc_sub_idx')],
            },
        ),
    ]
