# Generated by Django 4.2.8 on 2026-01-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidc',
            name='jti',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='oidc',
            constraint=models.UniqueConstraint(models.F('jti'), name='unique_jti_constraint'),
        ),
    ]
