# Generated by Django 4.2.8 on 2026-02-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0002_oidc_jti_oidc_unique_jti_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oidc',
            name='locale',
        ),
    ]
