# Generated by Django 4.2.8 on 2026-02-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0003_remove_oidc_locale'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='oidc',
            name='unique_jti_constraint',
        ),
    ]
