# Generated by Django 4.2.30 on 2026-06-14 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_role_description_en_role_description_fr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchInviteeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('organization_neomodel_uid', models.UUIDField()),
                ('user_uid', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.PositiveIntegerField()),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('successful_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('skipped_duplicate_email_count', models.PositiveIntegerField(default=0)),
                ('skipped_active_user_count', models.PositiveIntegerField(default=0)),
                ('failed_email_count', models.PositiveIntegerField(default=0)),
                ('role', models.CharField(max_length=50)),
                ('send_emails', models.BooleanField(default=True)),
                ('summary', models.JSONField(default=list)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
