# Generated by Django 5.2.17 on 2026-08-15 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_batchinviteejob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='label',
        ),
        migrations.RemoveField(
            model_name='role',
            name='label_en',
        ),
        migrations.RemoveField(
            model_name='role',
            name='label_fr',
        ),
    ]
