# Generated by Django 4.1.9 on 2023-06-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0017_legalentity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalentity',
            options={'verbose_name_plural': 'Legal entities'},
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='RNA',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
