# Generated by Django 4.1.9 on 2023-06-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0018_alter_legalentity_options_alter_legalentity_rna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='RCS',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='SHARE_CAPITAL',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='VAT',
            field=models.CharField(blank=True, help_text='VAT identification number', max_length=255, null=True, unique=True),
        ),
    ]
