# Generated by Django 4.2.8 on 2023-12-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0019_alter_legalentity_rcs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='neomodel_uid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
