# Generated by Django 4.1.11 on 2023-09-12 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facility', '0020_organization_administrators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='administrators',
            field=models.ManyToManyField(blank=True, related_name='administrator_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
