# Generated by Django 4.2.8 on 2025-08-02 16:58

from django.db import migrations, models
import easy_thumbnails.fields
import facility.models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0021_alter_facility_contact_alter_organization_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=facility.models.logo_path),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_alt',
            field=models.TextField(blank=True),
        ),
    ]
