# Generated by Django 4.2.8 on 2025-09-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0022_organization_logo_organization_logo_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='formatted_name_short',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='formatted_name_short_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='formatted_name_short_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
