# Generated by Django 4.2.8 on 2025-10-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0023_organization_formatted_name_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='formatted_name_short_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='formatted_name_short_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
