# Generated by Django 4.2.29 on 2026-04-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0023_organization_formatted_name_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='google_calendar_api_key',
            field=models.CharField(blank=True, help_text='Google Calendar API key', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='google_calendar_id',
            field=models.CharField(blank=True, help_text='Google Calendar ID', max_length=255),
        ),
    ]
