# Generated by Django 4.2.28 on 2026-05-13 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0024_alter_label_term_type'),
        ('facility', '0024_organization_google_calendar_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='directory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='directory.directory'),
        ),
    ]
