# Generated by Django 4.2.28 on 2026-05-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0025_add_directory_to_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sandbox',
            field=models.BooleanField(default=False, help_text='Auto-grant staff role to any authenticated user.'),
        ),
    ]
