# Generated by Django 4.2.30 on 2026-06-16 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0026_add_sandbox_to_organization'),
    ]

    operations = [
    ]
