# Generated by Django 4.2.30 on 2026-06-16 23:07

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0026_add_sandbox_to_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Europe/Paris', help_text='IANA timezone (e.g. Europe/Paris)'),
        ),
    ]
