# Generated by Django 4.2.30 on 2026-06-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0026_add_sandbox_to_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(max_length=63, default='Europe/Paris'),
        ),
    ]
