# Generated by Django 4.2.30 on 2026-06-17 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0027_organization_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='timezone',
        ),
    ]
