# Generated by Django 5.2.16 on 2026-08-03 03:44

import easy_thumbnails.fields
import facility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0028_remove_organization_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neomodel_uid', models.UUIDField(unique=True)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=facility.models.place_image_path)),
                ('alt', models.TextField(blank=True, help_text='Describes the picture to people who cannot see it.')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Place images',
            },
        ),
    ]
