# Generated by Django 5.2.17 on 2026-09-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0029_placeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='public_base_url',
            field=models.URLField(blank=True, help_text='Public URL of the site including any base path, e.g. https://unipa.fr/annuaire. Leave blank for https://{domain}. Used for links in emails: nginx strips the base path before requests reach the backend, so it cannot be derived from the Site.'),
        ),
    ]
