# Generated by Django 5.2.17 on 2026-09-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0030_organization_public_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email_template_editor_role',
            field=models.CharField(choices=[('administrator', 'Administrators and superusers'), ('superuser', 'Superusers only')], default='superuser', help_text="Who may change the organization's email templates and their images. Administrators and higher may always see and preview them.", max_length=16),
        ),
    ]
