# Generated by Django 5.2.17 on 2026-09-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0031_organization_email_template_editor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='entry_type_edit_days_administrator',
            field=models.PositiveSmallIntegerField(default=30, help_text="Days after an entry's creation during which an administrator may change its occupation. 0: never."),
        ),
        migrations.AddField(
            model_name='organization',
            name='entry_type_edit_days_connected',
            field=models.PositiveSmallIntegerField(default=7, help_text="Days after an entry's creation during which its creator or an owner may change its occupation. 0: never."),
        ),
    ]
