# Generated by Django 5.2.17 on 2026-09-30 16:17

import facility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0032_organization_entry_type_edit_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='Europe/Paris', help_text='IANA time zone, e.g. Europe/Paris, America/Martinique', max_length=64, validators=[facility.models.validate_timezone]),
        ),
    ]
