# Generated by Django 5.2.17 on 2026-10-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0033_organization_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='batch_invitation_max_rows',
            field=models.PositiveIntegerField(blank=True, help_text='Most rows one invitation spreadsheet may hold. Blank: the default (settings.BATCH_INVITATION_MAX_ROWS, 1000).', null=True),
        ),
    ]
