# Generated by Django 5.2.17 on 2026-10-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0034_organization_batch_invitation_max_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='reply_to_email',
            field=models.EmailField(blank=True, help_text="Where replies to the organization's email go. Mail is sent from a shared domain (noreply@mail.medica.im); blank: replies go to settings.MAIL_DEFAULT_REPLY_TO.", max_length=254),
        ),
    ]
